### ISSUE TITLE
Metadata examples are broken

### ISSUE THREAD

**Issue by MarkLodato** [in-toto/in-toto.github.io#17]
In the new site design[^1], the metadata examples no longer exist. For example, on https://in-toto.io/metadata-examples/, there exists a link to https://in-toto.io/examples/debian but the latter gives a 404. It used to work and is found in [Google search results](https://www.google.com/search?q=in-toto+debian+example).

[^1]: By the way, the new site is not reflected in this repo.

**Comment by lukpueh** [comment]
Thanks for the report, @MarkLodato!

The new website sources are hosted in [https://github.com/in-toto/in-toto.io](in-toto/in-toto.io). And the issue you kindly pointed out has been fixed with https://github.com/in-toto/in-toto.io/pull/4. You should be able to see the sample metadata under https://in-toto.io/metadata-examples/ now.
