### ISSUE TITLE
Cannot load `*.md` files, except for `index.md`

### ISSUE THREAD

**Issue by vladimir-v-diaz** [in-toto/in-toto.github.io#5]
The README states, "Adding content is as simple as creating *.html, or *.md files and filling them with content."

A `index.md` page can be loaded successfully, however, any other pages with a `.md` extension fail.

Interestingly, if a file contains Markdown content and you append a `.html` extension to its filename, it works.

**Comment by vladimir-v-diaz** [comment]
> Interestingly, if a file contains Markdown content and you append a .html extension to its filename, it works.

Never mind, the Markdown content doesn't always render correctly by simply appending the `.html` extension.

**Comment by lukpueh** [comment]
Jekylls converts markdown files to html and stores the result with an `.html` file extension to the `_site` directory. Processing is performed as soon as you add yaml front matter to a file's header.
```yaml
---
...
---
```
If there is no such header, the markdown file is just copied over to `_site` as is, without converting to html or changing the extension.

I can clarify they relevant section in the README (which btw. doesn't get copied to `_site` because it's excluded in [`_config.yml`](https://github.com/in-toto/in-toto.github.io/blob/master/_config.yml#L8)).
